baseURL = 'https://danielshoots.github.io/'
languageCode = 'en-us'
title = 'Daniel Shoots'
theme = "custom"
Paginate = 1000
googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

# this setting should always be set to false, otherwise it will break the section navigation bar
pluralizelisttitles = false

[params]
  author = "Daniel Scarfe"
  description = "Minimal, one page, theme for showcasing your work"
  message = "My page for sharing wildlife & travel photography, every once in a while."
  hideAutoMenu = false

  # Pagination options
  paginate = 12
  multipage = false

  # Dark mode
  darkMode = true

#[[menu.main]]
#  name = "External"
#  url = "https://example.com"

[footer]
  custom = "Hello World!"

[social]
#  email = "contact@danielshoots.com"
#  facebook = "https://facebook.com"
#  twitter = "https://twitter.com"
  instagram = "https://www.instagram.com/danielshootsphotos/"
  linkedin = "https://linkedin.com/in/daniel-scarfe"

